[info]
title = "外置登录服务器测试"

[info.contact]
link1 = "exmple.com"
link2 = "exmple.com"
link3 = "exmple.com"
link4 = "exmple.com"

[info.friend]
link1 = "exmple.com"
link2 = "exmple.com"
link3 = "exmple.com"
link4 = "exmple.com"
